### ISSUE TITLE
No open window with an HTML document Error

### ISSUE THREAD

**Issue by cxsquared** [katywings/adm-download-manager#1]
I just tried to run ./adm.sh -i for the first time and it threw an error when downloading current pack info.

\node_modules\zombie\lib\eventloop.js:594
            throw error;
            ^
AssertionError: No open window with an HTML document
    at Browser.querySelectorAll (C:\development\.babun\cygwin\home\cxsqu\node_modules\zombie\lib\index.js:521:7)
    at C:\development\.babun\cygwin\home\cxsqu\node_modules\adm-download-manager\adm.js:171:33
    at done (C:\development\.babun\cygwin\home\cxsqu\node_modules\zombie\lib\eventloop.js:589:11)
    at Timeout.timeout (C:\development\.babun\cygwin\home\cxsqu\node_modules\zombie\lib\eventloop.js:601:33)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

I'm running Windows 10 using Cygwin. The login process seemed to run fine but that's it.

Edit:
The issue seems to be with zombie and is related to this issue https://github.com/assaf/zombie/issues/953. Adding the waitDuration: 29*1000 seems to fix my issues.

**Comment by katywings** [comment]
Pull request merged! Thank you for your feedback <3
